### ISSUE TITLE
I cannot reproduce the reported results in the paper

### ISSUE THREAD

**Issue by hyoje42** [locuslab/orthogonal-convolutions#1]
Hi. Thank you for sharing the excellent work!
However, I cannot reproduce the performance of ResNet9 reported in your paper.
I used the command from your github page, 

`python train.py --epochs=200 --conv=CayleyConv --linear=CayleyLinear --model ResNet9`

the result is:
 
![image](https://user-images.githubusercontent.com/35217135/206463851-4578ec6d-1bb2-4fbc-9e96-a742b6d9f10b.png)

I interpreted the above result as a test accuracy is 72.27 %.
As I know, the reported result of ResNet9 is 81.70 +- 0.12
I tried various arguments like `epochs=100, lr_max=0.001, eps=0.0`, but it failed.
How can I reproduce the result for ResNet9 in your paper?

If I'm wrong, please let me know.
Thanks, in advance.

**Comment by ashertrockman** [comment]
As the ResNet9 results in the paper are for empirical rather than certifiable robustness, you should add the `--stddev` flag. Otherwise, we only subtract the mean from the inputs. I believe this will fix your problem.

Thanks for your interest in our work -- please let me know if this doesn't resolve your problem.

**Comment by hyoje42** [comment]
Thanks for your kind reply! I resolved the problem by using `--stddev`. 

By the way, I have a few additional questions.

1. Input Normalization
In your paper, you said that `Inputs to the model are always in the range [0; 1]` in Sec 5.1 Training Details. However, in your code, the model uses a normalization layer that subtracts the mean from the inputs(only KWLarge). Which one is right?
2. `--stddev`
As you say, ResNet9 use `--stddev`, which means inputs are scaled with standardization. But KWLarge architecture only subtracts the mean from the inputs. Is there any crucial reason? Or It is just a heuristic reason? 

Please let me know if I missed anything in your paper.
Thanks, in advance.

**Comment by ashertrockman** [comment]
1. We think of the normalization layer as part of the model. That is, the inputs to the model are in the range [0, 1], and the first layer of the model normalizes them. I think the next point makes this perspective more clear.
2. Yes, there is a crucial reason: For certifiable robustness, we want the model to be a composition of 1-Lipschitz functions; dividing by stddev is not 1-Lipschitz. For *empirical* robustness, we don't need to know these bounds, so we can do what's best for performance (which is dividing by stddev, as is typical in the non-robust setting).

I believe these (somewhat confusing) details come from the need to "standardize" the perturbation magnitude (epsilon). That is, you can only meaningfully compare epsilon = 36/255 Lp-certified robustness across papers if the input range is also the same.

**Comment by hyoje42** [comment]
I really appreciate your quick response and detailed explanation. It has been very helpful for me. Thank you so much!

**Comment by ashertrockman** [comment]
No problem! Let me know if you have any other questions.
